### ISSUE TITLE
Can't use {VOTER_NAME} in command part

### ISSUE THREAD

**Issue by yarik2720** [caxanga334/cvreduxmodified#14]
**Describe the bug**
In commands {VOTER_NAME} is not showing player name that started vote

**To Reproduce**
```
	"Mute player"
	{
		"type"			"players"
		"vote"			"1"
		"minimum"		"2"
		"cooldown"		"100"
		"ratio"			"0.64"
		"command"		"sm_silence #{TARGET_ID} 30 Muted by voting - {VOTER_NAME}"
		"start_notify"	"{olive}[SM] {default}{VOTER_NAME} started a vote to mute {red}{TARGET_NAME}{default}."
		"call_notify"	"{olive}[SM] {default}Vote cast for {yes|no}."
		"pass_notify"	"{olive}[SM] {default}Vote passed."
		"fail_notify"	"{olive}[SM] {default}Vote failed. Received: {VOTE_AMOUNT} Required: {VOTE_REQUIRED}"
		"chattrigger"	"votemute"
	}
```
 [SourceComms++] Console: Issued an extended silence on Fabler for 30 minutes (reason: Muted by voting - {VOTER_NAME}).

**Expected behavior**
[SourceComms++] Console: Issued an extended silence on Fabler for 30 minutes (reason: Muted by voting - Nickname).

**Screenshots**
![synergy_2019-04-05_21-07-14](https://user-images.githubusercontent.com/1839978/55648067-f4f0e280-57e7-11e9-92bb-82ad703244ad.png)

**Game Server**
* SourceMod Version: 1.10.0.6373
* Metamod:Source version 1.10.7-dev
* "Custom Votes" (1.16.3U) by ReFlexPoison,Anonymous Player
* Synergy

**Comment by caxanga334** [comment]
This could potentially allow people to run any commands on the server.

https://forums.alliedmods.net/showpost.php?p=2579011&postcount=270

This is the same reason you shouldn't use {TARGET_NAME} on **command**.

**Comment by yarik2720** [comment]
Ok, I understand. Issue can be closed
