### ISSUE TITLE
call_notify never procs

### ISSUE THREAD

**Issue by kikaragyozov** [caxanga334/cvreduxmodified#30]
The official version back in 2015 works, Your modifications break the call_notify for some reason, that is - you don't see a message of who voted what.

Could you investigate? Thanks.

**Comment by caxanga334** [comment]
From my testing on a clean install. Only the call_notify for simple votes targeting a convar does not work. This also applies to the original plugin since this part of the code was not changed.

**Comment by caxanga334** [comment]
I've pushed a fix. You can get the updated plugin from [the actions page](https://github.com/caxanga334/cvreduxmodified/actions/runs/2967297016).

**Comment by caxanga334** [comment]
Fix was implemented over a year ago. OP didn't confirm if the fix worked on their end. Closing as complete.
