### ISSUE TITLE
{CURRENT_MAP_NAME} doesnt work for voterestart

### ISSUE THREAD

**Issue by xeloth12** [caxanga334/cvreduxmodified#34]
**Describe the bug**
{CURRENT_MAP_NAME} cannot be used for map restarts. It doesn't work or sm_map and changelevel commands.

**To Reproduce**
1. Create custom vote
![image](https://github.com/caxanga334/cvreduxmodified/assets/131801544/ac9a2bb5-2155-420d-a043-69223d03c8ca)
2. Trigger by voterestart chat command
3. Error occurs on the server log
![image](https://github.com/caxanga334/cvreduxmodified/assets/131801544/b1d341cd-cac8-4f16-9876-e92258d9a23f)

**Expected behavior**
Map restarts.

**Game Server**
* Sourcemod version 1.11.0.6932
* Metamod version 1.11.0-dev+1148
* Custom Votes plugin version 1.19.4U
* Game: Dark Messiah of Might and Magic Multiplayer

**Additional context**
Let me know if it happens in other source games.

**Comment by caxanga334** [comment]
`{CURRENT_MAP_NAME}` is only formatted for 'map' vote type. Marking this as a feature request.

**Comment by caxanga334** [comment]
Please test and report if it works.
[cvreduxmodified_dev_issue34.zip](https://github.com/caxanga334/cvreduxmodified/files/13550292/cvreduxmodified_dev_issue34.zip)
